/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'couples' : null } |
  { 'prewedding' : null } |
  { 'senior' : null } |
  { 'monsoon' : null } |
  { 'friends' : null } |
  { 'family' : null };
export interface GalleryImage {
  'id' : bigint,
  'imageUrl' : string,
  'caption' : string,
  'category' : Category,
}
export interface Inquiry {
  'id' : bigint,
  'packageName' : string,
  'guestCount' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'message' : string,
  'preferredDate' : string,
  'phone' : string,
  'packageId' : bigint,
}
export interface Package {
  'id' : bigint,
  'duration' : string,
  'priceGroup' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'pricePerPerson' : bigint,
  'description' : string,
  'inclusions' : Array<string>,
  'category' : Category,
  'maxGuests' : bigint,
}
export interface Testimonial {
  'id' : bigint,
  'date' : string,
  'name' : string,
  'message' : string,
  'category' : Category,
  'rating' : bigint,
  'location' : string,
}
export interface _SERVICE {
  'getAllGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getGalleryImagesByCategory' : ActorMethod<[Category], Array<GalleryImage>>,
  'getPackageById' : ActorMethod<[bigint], [] | [Package]>,
  'getPackagesByCategory' : ActorMethod<[Category], Array<Package>>,
  'getTestimonialsByCategory' : ActorMethod<[Category], Array<Testimonial>>,
  'seed' : ActorMethod<[], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, bigint, string, bigint, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];