/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'couples' : IDL.Null,
  'prewedding' : IDL.Null,
  'senior' : IDL.Null,
  'monsoon' : IDL.Null,
  'friends' : IDL.Null,
  'family' : IDL.Null,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
  'category' : Category,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'packageName' : IDL.Text,
  'guestCount' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
  'packageId' : IDL.Nat,
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Text,
  'priceGroup' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'pricePerPerson' : IDL.Nat,
  'description' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'category' : Category,
  'maxGuests' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getGalleryImagesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'getPackageById' : IDL.Func([IDL.Nat], [IDL.Opt(Package)], ['query']),
  'getPackagesByCategory' : IDL.Func([Category], [IDL.Vec(Package)], ['query']),
  'getTestimonialsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'seed' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'couples' : IDL.Null,
    'prewedding' : IDL.Null,
    'senior' : IDL.Null,
    'monsoon' : IDL.Null,
    'friends' : IDL.Null,
    'family' : IDL.Null,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
    'category' : Category,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'packageName' : IDL.Text,
    'guestCount' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
    'packageId' : IDL.Nat,
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Text,
    'priceGroup' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'pricePerPerson' : IDL.Nat,
    'description' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'category' : Category,
    'maxGuests' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getGalleryImagesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'getPackageById' : IDL.Func([IDL.Nat], [IDL.Opt(Package)], ['query']),
    'getPackagesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Package)],
        ['query'],
      ),
    'getTestimonialsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'seed' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };