/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Package {
    id: bigint;
    duration: string;
    priceGroup: bigint;
    name: string;
    isAvailable: boolean;
    pricePerPerson: bigint;
    description: string;
    inclusions: Array<string>;
    category: Category;
    maxGuests: bigint;
}
export interface Inquiry {
    id: bigint;
    packageName: string;
    guestCount: bigint;
    name: string;
    submittedAt: bigint;
    message: string;
    preferredDate: string;
    phone: string;
    packageId: bigint;
}
export interface GalleryImage {
    id: bigint;
    imageUrl: string;
    caption: string;
    category: Category;
}
export interface Testimonial {
    id: bigint;
    date: string;
    name: string;
    message: string;
    category: Category;
    rating: bigint;
    location: string;
}
export enum Category {
    couples = "couples",
    prewedding = "prewedding",
    monsoon = "monsoon",
    friends = "friends",
    family = "family"
}
export interface backendInterface {
    getAllGalleryImages(): Promise<Array<GalleryImage>>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllPackages(): Promise<Array<Package>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getGalleryImagesByCategory(category: Category): Promise<Array<GalleryImage>>;
    getPackageById(id: bigint): Promise<Package | null>;
    getPackagesByCategory(category: Category): Promise<Array<Package>>;
    getTestimonialsByCategory(category: Category): Promise<Array<Testimonial>>;
    seed(): Promise<void>;
    submitInquiry(name: string, phone: string, packageId: bigint, packageName: string, guestCount: bigint, preferredDate: string, message: string): Promise<bigint>;
}
import type { Category as _Category, GalleryImage as _GalleryImage, Package as _Package, Testimonial as _Testimonial } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryImages();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryImages();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return result;
        }
    }
    async getAllPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPackages();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPackages();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryImagesByCategory(arg0: Category): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImagesByCategory(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImagesByCategory(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackageById(arg0: bigint): Promise<Package | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackageById(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackageById(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackagesByCategory(arg0: Category): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackagesByCategory(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackagesByCategory(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonialsByCategory(arg0: Category): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialsByCategory(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialsByCategory(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async seed(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seed();
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
}
function from_candid_Category_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_GalleryImage_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryImage): GalleryImage {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Package_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Package): Package {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Testimonial_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimonial): Testimonial {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Package]): Package | null {
    return value.length === 0 ? null : from_candid_Package_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: string;
    name: string;
    message: string;
    category: _Category;
    rating: bigint;
    location: string;
}): {
    id: bigint;
    date: string;
    name: string;
    message: string;
    category: Category;
    rating: bigint;
    location: string;
} {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        message: value.message,
        category: from_candid_Category_n4(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        location: value.location
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    imageUrl: string;
    caption: string;
    category: _Category;
}): {
    id: bigint;
    imageUrl: string;
    caption: string;
    category: Category;
} {
    return {
        id: value.id,
        imageUrl: value.imageUrl,
        caption: value.caption,
        category: from_candid_Category_n4(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    duration: string;
    priceGroup: bigint;
    name: string;
    isAvailable: boolean;
    pricePerPerson: bigint;
    description: string;
    inclusions: Array<string>;
    category: _Category;
    maxGuests: bigint;
}): {
    id: bigint;
    duration: string;
    priceGroup: bigint;
    name: string;
    isAvailable: boolean;
    pricePerPerson: bigint;
    description: string;
    inclusions: Array<string>;
    category: Category;
    maxGuests: bigint;
} {
    return {
        id: value.id,
        duration: value.duration,
        priceGroup: value.priceGroup,
        name: value.name,
        isAvailable: value.isAvailable,
        pricePerPerson: value.pricePerPerson,
        description: value.description,
        inclusions: value.inclusions,
        category: from_candid_Category_n4(_uploadFile, _downloadFile, value.category),
        maxGuests: value.maxGuests
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couples: null;
} | {
    prewedding: null;
} | {
    monsoon: null;
} | {
    friends: null;
} | {
    family: null;
}): Category {
    return "couples" in value ? Category.couples : "prewedding" in value ? Category.prewedding : "monsoon" in value ? Category.monsoon : "friends" in value ? Category.friends : "family" in value ? Category.family : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryImage>): Array<GalleryImage> {
    return value.map((x)=>from_candid_GalleryImage_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Package>): Array<Package> {
    return value.map((x)=>from_candid_Package_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimonial>): Array<Testimonial> {
    return value.map((x)=>from_candid_Testimonial_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    couples: null;
} | {
    prewedding: null;
} | {
    monsoon: null;
} | {
    friends: null;
} | {
    family: null;
} {
    return value == Category.couples ? {
        couples: null
    } : value == Category.prewedding ? {
        prewedding: null
    } : value == Category.monsoon ? {
        monsoon: null
    } : value == Category.friends ? {
        friends: null
    } : value == Category.family ? {
        family: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
